=== JBalaazs/ZUYISF_XMLGyak/XMLTaskZUYISF/XMLSchemaZUYISF.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--Egyszerű típusok kigyűjtése, saját típusok meghatározása, megszorítás-->
    <xs:element name="Szakterület" type="xs:string" />
    <xs:element name="Telefonszám" type="telefonszámTípus" />
    <xs:element name="Ügyvéd_Név" type="xs:string" />
    <xs:element name="Lakcím" type="xs:string" />
    <xs:element name="Szülidő" type="xs:date" />
    <xs:element name="Kor" type="xs:int" />
    <xs:element name="Priusz" type="priuszTipus" /> <!-- 1 vagy 0 | Van vagy nincs-->
    <xs:element name="Vád" type="xs:string" />
    <xs:element name="Típus" type="xs:string" />
    <xs:element name="Dátum" type="xs:date" />
    <xs:element name="Állapot" type="xs:string" />
    <xs:element name="Ügyek_száma" type="xs:string" />
    <xs:element name="Ítélet" type="xs:string" />
    <xs:element name="Bíró_Név" type="xs:string" />
    <xs:element name="Tapasztalat" type="xs:string" />
    <xs:element name="Tanítványok" type="xs:int" />
    <xs:element name="Jegyző_Név" type="xs:string" />
    <xs:element name="Munkaidő" type="xs:string" />
    <xs:element name="Nyelvtudás" type="xs:string" />


    <xs:simpleType name="telefonszámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+\d{11}" />
        </xs:restriction>
    </xs:simpleType>

    
    <xs:simpleType name="személyi_igTipus">
        <xs:restriction base="xs:string">
            <xs:length value="8" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="priuszTipus">
        <xs:restriction base="xs:boolean" />
    </xs:simpleType>


    <!--Komplex típusokhoz saját típus meghatározása, sorrendiség, számosság etc.-->
    <xs:complexType name="ÜgyvédTípus">
        <xs:sequence>
            <xs:element ref="Szakterület" />
            <xs:element ref="Telefonszám" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="Ügyvéd_Név" />
        </xs:sequence>
        <xs:attribute name="Ügyvédi_ID" type="xs:integer" use="required"/>
        <xs:attribute name="Védi" type="személyi_igTipus" use="required"/>
    </xs:complexType>


    <xs:complexType name="VádlottTípus">
        <xs:sequence>
            <xs:element ref="Lakcím" />
            <xs:element ref="Szülidő" />
            <xs:element ref="Kor" />
            <xs:element ref="Priusz" />
            <xs:element name="Név">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Vnév"/>
                        <xs:element name="Knév"/>
                    </xs:sequence>  
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="Személyi_ig" type="személyi_igTipus" use="required"/>
    </xs:complexType>


    <xs:complexType name="Bűnös-eTípus">
        <xs:sequence>
            <xs:element ref="Vád" />
        </xs:sequence>
        <xs:attribute name="Vádlott" type="személyi_igTipus" use="required"/>
        <xs:attribute name="Ügy" type="xs:integer" use="required"/>
    </xs:complexType>

    
    <xs:complexType name="ÜgyTípus">
        <xs:sequence>
            <xs:element ref="Típus" />
            <xs:element ref="Dátum" />
            <xs:element ref="Állapot" />
        </xs:sequence>
        <xs:attribute name="Ügyszám_ID" type="xs:integer" use="required" />
    </xs:complexType>


    <xs:complexType name="Ítéletet_hozTípus">
        <xs:sequence>
            <xs:element ref="Ügyek_száma" />
            <xs:element ref="Ítélet" />
        </xs:sequence>
        <xs:attribute name="Ügy" type="xs:integer" use="required" />
        <xs:attribute name="Bíró" type="xs:integer" use="required" />
    </xs:complexType>

    
    <xs:complexType name="BíróTípus">
        <xs:sequence>
            <xs:element ref="Bíró_Név" />
            <xs:element ref="Tapasztalat" />
            <xs:element ref="Tanítványok" />
        </xs:sequence>
        <xs:attribute name="Bíró_ID" type="xs:integer" use="required" />
    </xs:complexType>


    <xs:complexType name="JegyzőTípus">
        <xs:sequence>
            <xs:element ref="Jegyző_Név" />
            <xs:element ref="Munkaidő" />
            <xs:element ref="Nyelvtudás" />
        </xs:sequence>
        <xs:attribute name="Jegyző_ID" type="xs:integer" use="required" />
        <xs:attribute name="Rögzítés" type="xs:integer" use="required" />
    </xs:complexType>


    <!--Gyökérelemtől az elemek felhasználása-->
    <xs:element name="Tárgyalás_ZUYISF">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ügyvéd" type="ÜgyvédTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Vádlott" type="VádlottTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Bűnös-e" type="Bűnös-eTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Ügy" type="ÜgyTípus" minOccurs="1" maxOccurs="unbounded"/> 
                <xs:element name="Ítéletet_hoz" type="Ítéletet_hozTípus" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="Bíró" type="BíróTípus" minOccurs="1" maxOccurs="1"/>
                <xs:element name="Jegyző" type="JegyzőTípus" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>


    <!--Elsődleges kulcsok-->
    <xs:key name="Ügyvéd_kulcs">
        <xs:selector xpath="Ügyvéd" />
        <xs:field xpath="@Ügyvédi_ID" />
    </xs:key>

    <xs:key name="Vádlott_kulcs">
        <xs:selector xpath="Vádlott" />
        <xs:field xpath="@Személyi_ig" />
    </xs:key>

    <xs:key name="Ügy_kulcs">
        <xs:selector xpath="Ügy" />
        <xs:field xpath="@Ügyszám_ID" />
    </xs:key>

    <xs:key name="Bíró_kulcs">
        <xs:selector xpath="Bíró" />
        <xs:field xpath="@Bíró_ID" />
    </xs:key>

    <xs:key name="Jegyző_kulcs">
        <xs:selector xpath="Jegyző" />
        <xs:field xpath="@Jegyző_ID" />
    </xs:key>


    <!--Idegen kulcsok-->
    <xs:keyref name="Vádlott_Ügyvéd_kulcs" refer="Vádlott_kulcs">
        <xs:selector xpath="Ügyvéd" />
        <xs:field xpath="@Védi" />
    </xs:keyref>

    <xs:keyref name="Bünös-e_Vádlott_kulcs" refer="Vádlott_kulcs">
        <xs:selector xpath="Bűnös-e" />
        <xs:field xpath="@Vádlott" />
    </xs:keyref>

    <xs:keyref name="Bünös-e_Ügy_kulcs" refer="Ügy_kulcs">
        <xs:selector xpath="Bűnös-e" />
        <xs:field xpath="@Ügy" />
    </xs:keyref>

    <xs:keyref name="Ügy_Ítéletet_hoz_kulcs" refer="Ügy_kulcs">
        <xs:selector xpath="Ítéletet_hoz" />
        <xs:field xpath="@Ügy" />
    </xs:keyref>

    <xs:keyref name="Bíró_Ítéletet_hoz_kulcs" refer="Bíró_kulcs">
        <xs:selector xpath="Ítéletet_hoz" />
        <xs:field xpath="@Bíró" />
    </xs:keyref>

    <xs:keyref name="Bíró_Jegyző_kulcs" refer="Bíró_kulcs">
        <xs:selector xpath="Jegyző" />
        <xs:field xpath="@Rögzítés" />
    </xs:keyref>



    </xs:element>

</xs:schema>

=== JBalaazs/ZUYISF_XMLGyak/XMLTaskZUYISF/DOMParseZUYISF/XMLZUYISF.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Tárgyalás_ZUYISF xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaZUYISF.xsd">

    <!--Ügyvéd-->
    <Ügyvéd Védi="456789AB" Ügyvédi_ID="1">
    
        <Szakterület>Büntetőjog</Szakterület>

        <Telefonszám>+36204579450</Telefonszám>
        <Telefonszám>+36304796185</Telefonszám>
        <Telefonszám>+36507963418</Telefonszám>

        <Ügyvéd_Név>Dr. Kovács Mihály</Ügyvéd_Név>
    
    </Ügyvéd>

    <Ügyvéd Védi="785216CD" Ügyvédi_ID="2">
    
        <Szakterület>Szabálysértési jog</Szakterület>

        <Telefonszám>+36709614250</Telefonszám>
        <Telefonszám>+36704987134</Telefonszám>
        <Telefonszám>+36207943157</Telefonszám>

        <Ügyvéd_Név>Dr. Tóth Eszter</Ügyvéd_Név>

    </Ügyvéd>

    <!--Vádlott-->
    <Vádlott Személyi_ig="456789AB">

        <Lakcím>1111 Budapest, Jókai Mór u. 51</Lakcím>
        <Szülidő>1971-10-11</Szülidő>
        <Kor>52</Kor>
        <Priusz>0</Priusz>
        <Név>
            <Vnév>Kovács</Vnév>
            <Knév>Ferenc</Knév>
        </Név>

    </Vádlott>

    <Vádlott Személyi_ig="785216CD">

        <Lakcím>3525 Miskolc, Aba u. 12</Lakcím>
        <Szülidő>1999-05-21</Szülidő>
        <Kor>24</Kor>
        <Priusz>1</Priusz>
        <Név>
            <Vnév>Kiss</Vnév>
            <Knév>Tamás</Knév>
        </Név>

    </Vádlott>

    <!--Bűnös-e-->
    <Bűnös-e Vádlott="456789AB" Ügy="3000">

        <Vád>Súlyos testi sértés</Vád>

    </Bűnös-e>

    <Bűnös-e Vádlott="785216CD" Ügy="3001">

        <Vád>Közlekedési szabálysértés</Vád>

    </Bűnös-e>

    <!--Ügy-->
    <Ügy Ügyszám_ID="3000">
    
        <Típus>Büntetőjogi eljárás</Típus>
        <Dátum>2023-11-09</Dátum>
        <Állapot>Folyamatban</Állapot>
    
    </Ügy>

    <Ügy Ügyszám_ID="3001">
    
        <Típus>Szabálysértési eljárás</Típus>
        <Dátum>2023-08-16</Dátum>
        <Állapot>Elbírálás alatt</Állapot>
    
    </Ügy>

    <!--Ítéletet_hoz-->
    <Ítéletet_hoz Bíró="1000" Ügy="3000">
    
        <Ügyek_száma>6</Ügyek_száma>
        <Ítélet>Bűnösnek találtatik a vádlott, 2 év felfüggesztett szabadságvesztésre ítélve.</Ítélet>
    
    </Ítéletet_hoz>

    <Ítéletet_hoz Bíró="1000" Ügy="3001">
        
        <Ügyek_száma>4</Ügyek_száma>
        <Ítélet>Bírság megfizetésére kötelezve, 100 000 forint összegben.</Ítélet>

    </Ítéletet_hoz>

    <!--Bíró-->
    <Bíró Bíró_ID="1000">
        
        <Bíró_Név>Dr. Varga Klára</Bíró_Név>
        <Tapasztalat>15 év</Tapasztalat>
        <Tanítványok>3</Tanítványok>

    </Bíró>

    <!--Jegyző-->
    <Jegyző Jegyző_ID="100" Rögzítés="1000">
    
        <Jegyző_Név>Dr. Tóth Lilla</Jegyző_Név>
        <Munkaidő>Teljes munkaidő</Munkaidő>
        <Nyelvtudás>Angol, Német, Francia</Nyelvtudás>

    </Jegyző>


</Tárgyalás_ZUYISF>
